INSERT INTO FOOD_TRUCK (NAME, TRUCK_TYPE, LATITUDE, LONGITUDE)
    VALUES('Crazy Chicken Waffle', 0, 34.083170, -118.191783);
INSERT INTO FOOD_TRUCK (NAME, TRUCK_TYPE, LATITUDE, LONGITUDE)
    VALUES('OMG Sushi', 1, 34.08061, -118.178350);

INSERT INTO FOOD_ITEM (NAME, PRICE, TRUCKID) VALUES('Spicy Chicken and Waffle', 1000, 1);
INSERT INTO FOOD_ITEM (NAME, PRICE, TRUCKID) VALUES('Regular Chicken and Waffle', 900, 1);

INSERT INTO FOOD_ITEM (NAME, PRICE, TRUCKID) VALUES('Spicy Tuna', 200, 2);
INSERT INTO FOOD_ITEM (NAME, PRICE, TRUCKID) VALUES('OMG Roll', 500, 2);