INSERT INTO FOOD_TRUCK (NAME, TRUCK_TYPE) VALUES('Crazy Chicken Waffle', 0);
INSERT INTO FOOD_TRUCK (NAME, TRUCK_TYPE) VALUES('OMG Sushi', 1);

INSERT INTO FOOD_ITEM (NAME, PRICE, TRUCKID) VALUES('Spicy Chicken and Waffle', 1000, 1);
INSERT INTO FOOD_ITEM (NAME, PRICE, TRUCKID) VALUES('Regular Chicken and Waffle', 900, 1);

INSERT INTO FOOD_ITEM (NAME, PRICE, TRUCKID) VALUES('Spicy Tuna', 200, 2);
INSERT INTO FOOD_ITEM (NAME, PRICE, TRUCKID) VALUES('OMG Roll', 500, 2);