CREATE TABLE FOOD_TRUCK(
  TRUCKID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(128),
  TRUCK_TYPE SMALLINT,
  TIME_OPEN BIGINT,
  TIME_CLOSED BIGINT,
  LATITUDE DECIMAL(9,6),
  LONGITUDE DECIMAL(9,6)
);
CREATE TABLE FOOD_ITEM(
  ITEMID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(128),
  PRICE BIGINT,
  TRUCKID BIGINT,
  FOREIGN KEY(TRUCKID) REFERENCES FOOD_TRUCK(TRUCKID)
);

