CREATE TABLE FOOD_TRUCK(
  TRUCKID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(128),
);
CREATE TABLE FOOD_ITEM(
  ITEMID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(128),
  PRICE BIGINT,
  TRUCKID BIGINT,
  FOREIGN KEY(TRUCKID) REFERENCES FOOD_TRUCK(TRUCKID)
);

